name: Elixir CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test - Elixir ${{matrix.elixir}} / OTP ${{matrix.otp}}

    strategy:
      matrix:
        include:
          - elixir: 1.10.x
            otp: 22.x
          - elixir: 1.12.x
            otp: 23.x
          - elixir: 1.14.x
            otp: 24.x

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/checkout@v3

      - name: Cache Dependencies
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix deps.get
          mix deps.compile

      - run: gcc --version
      - run: mix compile --warnings-as-errors
      - run: mix test --exclude skip:true --trace

  lint:
    runs-on: ubuntu-22.04
    name: Lint
    strategy:
      matrix:
        include:
          - elixir: 1.14.x
            otp: 25.x
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - uses: actions/checkout@v3

      - name: Cache Dependencies
        id: mix-cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}

      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix deps.get
          mix deps.compile
          mix dialyzer --plt

      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix format --check-formatted
      - run: mix credo --strict
      - run: mix dialyzer --plt
